### ISSUE TITLE
cant install with vite4 and sveltekit 1.0

### ISSUE THREAD

**Issue by pgcr71** [vite-pwa/sveltekit#18]
dependencies:
+ vite-plugin-pwa 0.13.3 (0.14.0 is available)

 WARN  Issues with peer dependencies found
.
├─┬ @vite-pwa/sveltekit 0.0.1
│ └── ✕ missing peer @types/workbox-build@^5.0.1
└─┬ vite-plugin-pwa 0.13.3
  └── ✕ unmet peer vite@^3.1.0: found 4.0.2
Peer dependencies that should be installed:
  @types/workbox-build@^5.0.1

**Comment by robhicks** [comment]
Please merge #14.

**Comment by userquin** [comment]
released 0.1.0 version
