### ISSUE TITLE
SvelteKit 1.3.1+ not working

### ISSUE THREAD

**Issue by userquin** [vite-pwa/sveltekit#21]
SvelteKit 1.3.1 change: SSR build happens before the client-side build

**Comment by userquin** [comment]
The workaround is downgrade to 1.3.0, we're working to fix it.

**Comment by benmccann** [comment]
This looks like a regression in SvelteKit. We're now running the adapter in `writeBundle`, which is too early: 

https://github.com/sveltejs/kit/blob/fb24644b66f0411548dbb8e56b88d5e194d4086f/packages/kit/src/exports/vite/index.js#L566

We previously ran it in `closeBundle`:

https://github.com/sveltejs/kit/blob/a48efda2a12b06f53f6e02736266c189cdddfafa/packages/kit/src/exports/vite/index.js#L650

**Comment by benmccann** [comment]
Oh, wait. I take that back. We're just creating a `finalise` hook in `writeBundle`, but it doesn't get invoked until `closeBundle`:

https://github.com/sveltejs/kit/blob/fb24644b66f0411548dbb8e56b88d5e194d4086f/packages/kit/src/exports/vite/index.js#L726

**Comment by userquin** [comment]
It seems a regression in 1.3.1: kit `closeBundle` hook is called only on client build, and must be called only in server build.

**Comment by benmccann** [comment]
Please try with `@sveltejs/kit` version 1.3.7

**Comment by userquin** [comment]
@benmccann adapter still being called before pwa plugin, I'll try with a fresh install.

**Comment by benmccann** [comment]
The problem is that the PWA plugin is generating its files after SvelteKit calls `await vite.build` to invoke the client build and it returns. There's probably a missing `await` somewhere in Vite or the PWA plugin or something. Everything in SvelteKit looks okay as far as I can tell.

**Comment by benmccann** [comment]
This is a bug in Vite. It's not using an `await` when calling `bundle.close()`

**Comment by drewbitt** [comment]
This issue title & post is not descriptive; is this related to this error in Sveltekit on recent versions?
```
pnpm add @vite-pwa/sveltekit -D
# add SvleteKitPWA to vite.config.ts as in docs
pnpm run dev

failed to load config from C:\GitHub\MyStuff\Someplice\vite.config.ts
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite-plugin-pwa' 
```

**Comment by userquin** [comment]
@drewbitt

This issue is about kit and vite changes breaking the pwa plugin . It seems Vite bug is fixed, now we need to update this plugin to run with latest kit changes, check PR pages, we need to review a few things and we should release a new version soon.
