### ISSUE TITLE
PWA runs before prerendered pages are generated

### ISSUE THREAD

**Issue by RyanZhiNie** [vite-pwa/sveltekit#27]
I found that PWA sveltekit runs before prerendered pages are generated, so those pages are not included in the manifest. Maybe this issue is related to sveltekit updates, I didn't see this warning before.

![image](https://user-images.githubusercontent.com/25318236/217215190-d175bebf-359e-4954-ab44-6605940b7a11.png)

My current dependency versions:
```json
"devDependencies": {
                "@sveltejs/adapter-node": "^1.1.7",
		"@sveltejs/kit": "^1.5.0",
		"@vite-pwa/sveltekit": "^0.1.2",
		"svelte": "^3.55.1",
		"svelte-check": "^3.0.3",
		"vite": "^4.1.1",
		"vite-plugin-pwa": "^0.14.1",
		"workbox-window": "^6.5.4"
},
```

**Comment by userquin** [comment]
This is expected, you should have 2 builds, client and server, that warning should be only on client build:
- kit client build (vite write bundle hook)
- pwa build  (vite close bundle hook)<== your warning
- kit server build  (vite write bundle hook)
- kit prerender  (vite write bundle hook)
- pwa build  (vite close bundle hook: sequential to true with order pre)
- kit adapter (vite close bundle hook: sequential to true with no order)
