### ISSUE TITLE
example/sveltekit-ts doesn't preview on fresh clone (url not precahed)

### ISSUE THREAD

**Issue by GaryB432** [vite-pwa/sveltekit#29]
I would expect the sample to work out of the box

## Steps to reproduce

```
git clone https://github.com/vite-pwa/sveltekit.git
cd .\sveltekit\examples\sveltekit-ts\
npm install
npm install @vite-pwa/sveltekit -D
npm run build
npm run preview
```

## Error

build warning

```
PWA v0.14.3
mode      injectManifest
precache  41 entries (861.89 KiB)
files generated
  .svelte-kit\output\client\prompt-sw.js
warnings
  One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": ".svelte-kit/output",
  "globPattern": "prerendered/**/*.html",
  "globIgnores": [
    "**/node_modules/**/*",
    "client/prompt-sw.js",
    "client/prompt-sw.js"
  ]
}
```

appears in dev tools

```
Uncaught non-precached-url: createHandlerBoundToURL('/') was called, but that URL is not precached. Please pass in a URL that is precached instead.
    at PrecacheController.createHandlerBoundToURL (http://localhost:4173/prompt-sw.js:1493:13)
    at createHandlerBoundToURL (http://localhost:4173/prompt-sw.js:2079:30)
    at http://localhost:4173/prompt-sw.js:2176:3
```

Node : 18.7.0
OS : win32 x64
npm :  8.16.0

**Comment by userquin** [comment]
@GaryB432 can you check the version of SvelteKit? We're trying to fix this plugin, latest SvelteKit changes breaks pwa plugin

**Comment by GaryB432** [comment]
```
+-- @sveltejs/adapter-static@1.0.6
| `-- @sveltejs/kit@1.5.3 deduped
+-- @sveltejs/kit@1.5.3
`-- @vite-pwa/sveltekit@0.1.3
  `-- @sveltejs/kit@1.5.3 deduped
```

**Comment by userquin** [comment]
@GaryB432 I Will check it tmr

**Comment by userquin** [comment]
@GaryB432 I cannot reproduce your warning, SvelteKit do 2 builds, your warning can be shown when building the client, since SvelteKit prerender process has not yet run, and so, prerendered folder missing: check this response https://github.com/vite-pwa/sveltekit/issues/27#issuecomment-1420550146

**Comment by GaryB432** [comment]
Thanks for looking! That makes sense for the _warning_ for the server build phase.  My bigger issue is the `uncaught non-precached-url` _error_ in the browser dev tools that is keeping the example from running. Is that one reproducable?

**Comment by userquin** [comment]
@GaryB432 I sent a new PR, maybe it is related with your problem https://github.com/vite-pwa/sveltekit/pull/30, with that patch it is working, not tested with current version:

![imagen](https://user-images.githubusercontent.com/6311119/218141883-1f8d32ff-0f6a-4bb0-9de6-6f0897d7be9c.png)

**Comment by GaryB432** [comment]
That is a beautiful screenshot.  I will monitor the PR and try again when merged.  thanks!

**Comment by GaryB432** [comment]
monkey-patching and observing `createManifestTransform`, I see that all the `entries` have urls that start with `client/` and none of them end with `.html`.  Not event `index.html` is in `entries`. No `prerendered` or anything else in the sample. So the `if` block is set up for other adapters (?? over my head!)  Maybe that's related to the `createHandlerBoundToURL('/')` not finding `/`.

**Comment by userquin** [comment]
yes, you can provide your own manifestTransform, copy the one in the PR and add it on `workbox: { manifestTransform: [] }` array, it should work

**Comment by GaryB432** [comment]
It is the one from the PR that does not include `index.html` in `entries` so line 88 is not hit. I don't know enough about the `output` folder or sveltekit internals yet to know how to add it.  Moreover, I am unsure the sample is more than a suggestion and should work out of the box (my assumption) is correct.

**Comment by userquin** [comment]
@GaryB432 
Try this, add it to your pwa options, if workbox present just copy the manifestTransform array (ignoring sveltekit options, I just review the options and update the values: `suffix: '', adapterFallback: false`):
```ts
workbox: {
  manifestTransform: [async (entries) => {
        const defaultAdapterFallback = 'prerendered/fallback.html'
        const suffix = '' // options?.trailingSlash === 'always' ? '/' : ''
        let adapterFallback = false // options?.adapterFallback
        let excludeFallback = false
        // the fallback will be always generated by SvelteKit.
        // The adapter will copy the fallback only if it is provided in its options: we need to exclude it
        if (!adapterFallback) {
          adapterFallback = defaultAdapterFallback
          excludeFallback = true
        }

        // the fallback will be always in .svelte-kit/output/prerendered/fallback.html
        const manifest = entries.filter(({ url }) => !(excludeFallback && url === defaultAdapterFallback)).map((e) => {
        let url = e.url
        // client assets in `.svelte-kit/output/client` folder.
        // SSG pages in `.svelte-kit/output/prerendered/pages` folder.
        // fallback page in `.svelte-kit/output/prerendered` folder (fallback.html is the default).
        if (url.startsWith('client/'))
          url = url.slice(7)

        else if (url.startsWith('prerendered/pages/'))
          url = url.slice(18)

        else if (url === defaultAdapterFallback)
          url = adapterFallback!

        if (url.endsWith('.html')) {
          if (url.startsWith('/'))
            url = url.slice(1)

          if (url === 'index.html') {
            url = base
          }
          else {
            const idx = url.lastIndexOf('/')
            if (idx > -1) {
              // abc/index.html -> abc/?
              if (url.endsWith('/index.html'))
                url = `${url.slice(0, idx)}${suffix}`
              // abc/def.html -> abc/def/?
              else
                url = `${url.substring(0, url.lastIndexOf('.'))}${suffix}`
            }
            else {
              // xxx.html -> xxx/?
              url = `${url.substring(0, url.lastIndexOf('.'))}${suffix}`
            }
          }
        }

        e.url = url

        return e
      })

      return { manifest }
  }],
}

**Comment by GaryB432** [comment]
hmmm..  `Cannot find name "base"`  and `Type 'string' is not assignable to type 'boolean'.` for `adapterFallback` in a couple places.

**Comment by userquin** [comment]
Change `url = base` with `base = '/'`

**Comment by userquin** [comment]
> hmmm.. `Cannot find name "base"` and `Type 'string' is not assignable to type 'boolean'.` for `adapterFallback` in a couple places. (clarifying I am trying to build `examples/sveltekit-ts` on a fresh clone.)

Yes, I configure previous manifestTransform using the example, no fallback and no suffix, I forgot to replace `base`  with `'/'`...

**Comment by GaryB432** [comment]
I added `const base = '/'` and also, because `adapterFallback` is now a boolean and not assignable to `url`, I replaced `else if (url === defaultAdapterFallback) url = adapterFallback!` with `else if (url === defaultAdapterFallback) throw new Error("defaultAdapterFallback is not supported")`.

Still getting `Uncaught non-precached-url: createHandlerBoundToURL('/') was called, but that URL is not precached.` as in the OP

**Comment by userquin** [comment]
configure `navigateFallback: null`

**Comment by GaryB432** [comment]
I am not sure what that means. I wound up using the built-in service worker and making my own webmanifest per their documentation.  I'll try `vite-pwa` again some day if I see the this issue closed, i.e., the example runs.

**Comment by chooco13** [comment]
As I continued testing, I found out that the problem was caused by missing index.html.

I forcibly added processing for index.html as follows.
As a result, it worked normally.

demo
https://my-dashboard-r96qwqiv0-chooco13.vercel.app/

```
// vite.config.ts

    injectManifest: {
        globPatterns: ["client/**/*.{js,css,ico,png,svg,webp,woff,woff2}"],
        manifestTransforms: [
          async (entries) => {
            entries.push({
              url: "/index.html",
              revision: null,
              size: 0,
            });

            // the fallback will be always in .svelte-kit/output/prerendered/fallback.html
            const manifest = entries
              .map((e) => {
                let url = e.url;
                console.log(url);

                if (url.startsWith("client/")) {
                  url = url.slice(7);
                } else if (url.startsWith("prerendered/pages/")) {
                  url = url.slice(18);
                }

                if (url.endsWith(".html")) {
                  if (url.startsWith("/")) {
                    url = url.slice(1);
                  }

                  if (url === "index.html") {
                    url = "/";
                  } else {
                    const idx = url.lastIndexOf("/");
                    if (idx > -1) {
                      // abc/index.html -> abc/?
                      if (url.endsWith("/index.html")) {
                        url = `${url.slice(0, idx)}`;
                      } // abc/def.html -> abc/def/?
                      else {
                        url = `${url.substring(0, url.lastIndexOf("."))}`;
                      }
                    } else {
                      // xxx.html -> xxx/?
                      url = `${url.substring(0, url.lastIndexOf("."))}`;
                    }
                  }
                }

                e.url = url;

                return e;
              });

            return { manifest };
          },
        ],
      },
```
