### ISSUE TITLE
Use with Github-pages/subroutes

### ISSUE THREAD

**Issue by AKuederle** [vite-pwa/sveltekit#36]
First of all, thank you very much for creating this package! I currently trying to use it to create a small PWA hosted via github-pages.

However, this means that the app will served under a subdomain. As per the sveltekit documentation I configured the base path (`kit.paths.base` in `svelte.config.js`) accordingly.
Unfortunately this seems to break vite-pwa. Looking at the logs, the app still tries to pull the manifest, the `sw.js`, and icons from the url root and not the configured base-path.

I could not find any further information about this and I have limited knowledge of creating PWAs. So it might be that I just require an additional setting that I am missing.

I would appreciate any pointer in the right direction :)

**Comment by userquin** [comment]
@AKuederle try to configure scope pwa option  with the base path configured in kit config.

**Comment by AKuederle** [comment]
Thank you very much for the fast response. The `scope` option didn't help, but setting the `base` option in the `SvelteKitPWA` plugin seems to solve the above issue. This way the manifest and the assets seemed to be served correctly.

For some reason I thought, that the default for this setting (`vite.base`) would have been already set by sveltekit itself. But it seems not to be the case.

However, even with these settings, offline access does not seem to work. This seems to be independent of the base-path though. So it is likely a different issue. But basically it seems like the service worker caches everything BUT the actual index.html file generated during build does not seem to be cached by the service worker, resulting in `non-prechached-url` error on a repeated app load.

**Comment by AKuederle** [comment]
Ok I solved the issue! But maybe this is interesting for others:

I forgot to mark my page as prerenderable, (`export const prerender = true` in `+layout.ts`) and instead set a fallback page in the adapter static configuration. This allows the static build to succeed, but because the page is not marked as prerenderable, it is not added to the service worker cache.

I don't know if this is the intended interaction, but making sure to mark all my pages to be pre-rendered solved my issue.

@userquin Do you think this is something worth adding to the documentation somewhere? I am happy to contribute a paragraph.

**Comment by userquin** [comment]
@AKuederle you can send a PR to docs repo, to use precaching we need at least 1 html page, so you need at least 1 page with `prerender = true`: check [this PR](https://github.com/vite-pwa/docs/pull/36) as an example to use PWA plugin without precaching (not kit releated)

On kit, if you're not using precaching, you can use kit service worker implementation instead using this integration.

**Comment by drewbitt** [comment]
@userquin This 100% should be in docs. I just set it up with "Zero Config", no SvelteKitPWA() settings, which does not work; it shows a warning when no document is prerendered e.g. 

```
warnings
  One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "C:/Users/andys-pc/GitHub/MyStuff/Someplice/.svelte-kit/output",
  "globPattern": "prerendered/**/*.html",
  "globIgnores": [
    "**/node_modules/**/*",
    "server/sw.js",
    "server/workbox-*.js"
  ]
}
```

but it is not documented that this is required. And in fact in my simple Sveltekit app, even prerendering a page my PWA does not show up in browser. The requirement of a service worker config and/or `vite.base` and/or `prerender` is not obvious... docs make this seem like zero-config should work.
