### ISSUE TITLE
generateSW is not working in version 0.2.0

### ISSUE THREAD

**Issue by hawk93** [vite-pwa/sveltekit#37]
When building the application manifest.webmanifest file is added twice to cached file list, that causes an error and the app become unavailable offline.

I created a [repo](https://github.com/hawk93/vite-pwa-sveltekit-example) using the official sveltekit skeleton app and a minimal configuration that you can use to verify the problem. You just need to build and preview the application to obtain the error:

> Uncaught (in promise) add-to-cache-list-conflicting-entries: add-to-cache-list-conflicting-entries

**Comment by userquin** [comment]
@hawk93 checking latest kit changes, it is weird, the example here using kit `v1.11.0` is working...

**Comment by userquin** [comment]
ok, the problem is there, the web manifest is added twice, but with your reproduction the hash changes, and that's the problem, using the example here works with duplicated entry:

![imagen](https://user-images.githubusercontent.com/6311119/227715644-1e1bb437-757e-4ed6-8527-8aae39b51af3.png)

**Comment by userquin** [comment]
@hawk93 your repro using local copy from #38, web manifest added only once, I'm going to publish a new patch version:

![imagen](https://user-images.githubusercontent.com/6311119/227717863-f19413ca-9238-40ab-a936-2214e2b1b785.png)

**Comment by userquin** [comment]
tested also with new patch version: https://github.com/vite-pwa/sveltekit/releases/tag/v0.2.1

**Comment by hawk93** [comment]
@userquin I tested it too. It works now
