### ISSUE TITLE
Firefox Type Error

### ISSUE THREAD

**Issue by haleksandre** [vite-pwa/sveltekit#40]
The service worker doesn't register in Firefox browser when `injectManifest` mode is on. It fails with an `SW registration error TypeError: ServiceWorker script at http://localhost:5173/dev-sw.js?dev-sw for scope http://localhost:5173/ threw an exception during script evaluation.` error.

Any idea why the `injectManifest` mode doesn't register properly in Firefox?

**Comment by userquin** [comment]
@haleksandre if you're using static imports in your custom sw, you need to test it in chromium based browser (FF and Safari doesn't support type module in sw yet), you need to add `type: 'module' in `devOptions`.

**Comment by haleksandre** [comment]
That is it, I've missed the `type: module` info within the parentheses. Thanks for the quick reply!
