### ISSUE TITLE
Having an issue with ssr = false

### ISSUE THREAD

**Issue by hamishjohnson** [vite-pwa/sveltekit#52]
I'm trying to get this package working with a SPA with `export const ssr = false;` but it doesn't seem to be working when deployed. It works fine in dev mode.

I get this error
```
workbox-3625d7b0.js:1 Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"/"}]
    at O.createHandlerBoundToURL (https://test-sveltkit-gfjc7ulcj-hamishjohnson.vercel.app/workbox-3625d7b0.js:1:13245)
    at Object.createHandlerBoundToURL (https://test-sveltkit-gfjc7ulcj-hamishjohnson.vercel.app/workbox-3625d7b0.js:1:14916)
    at https://test-sveltkit-gfjc7ulcj-hamishjohnson.vercel.app/sw.js:1:3190
```

And so I tried prerendering the homepage but kept getting further precache issues

Here's an example repo https://github.com/hamishjohnson/test-sveltkit-pwa

And here it is deployed: https://test-sveltkit-gfjc7ulcj-hamishjohnson.vercel.app/ with errors in console

**Comment by userquin** [comment]
@hamishjohnson if you're using precaching you need 1 route as fallback, by default is the entry point: you need to prerender 1 route

**Comment by userquin** [comment]
it seems kit 1.5.0 has some problems with SSR builds, if you check the sw it includes server assets... can you try updating to latest version?

Tried with adapter node and same result...

**Comment by hamishjohnson** [comment]
Yeah I tried it with prerendering the root page in +page.ts.

And I just tried in both 1.16.3 and 1.14 but I'm experiencing the same problem. In each version when running build the server files get included which also confused me but that seems to have always been the case as seen here https://github.com/sveltejs/kit/issues/9161

**Comment by userquin** [comment]
@hamishjohnson you can solve server assets including `globIgnores`: 
```ts
      workbox: {
        globPatterns: ["client/**/*.{js,css,html,ico,png,svg}"],
        globIgnores: ["server/*.*"] // <== to remove server entries from sw precache manifest
      },
```

Since you're using `auto` adapter, there is no way to copy `prerendered/pages/index.html` to the output folder: you must copy it manually, the `navigateFallback` is properly added to sw precache manifest (just check `.sveltekit/output/client/` folder).

Using `node` adapter also works, the output folder will be `build`, but same problem with prerendered page.

**Comment by userquin** [comment]
uhmm, node adapter should work, I'll test it later:

![imagen](https://github.com/vite-pwa/sveltekit/assets/6311119/320e9499-eeaf-4711-abd1-67f5d2a35b36)

**Comment by userquin** [comment]
it works:

![imagen](https://github.com/vite-pwa/sveltekit/assets/6311119/82d7500d-ee88-4c27-acee-21d5b205b24c)

**Comment by hamishjohnson** [comment]
Ah :) The glob ignore worked for me, so I didn't try the Node Adapter, though I did try that before. Thanks for your help! I guess it should be documented.
