### ISSUE TITLE
Deprecated packages

### ISSUE THREAD

**Issue by Naviamold1** [vite-pwa/sveltekit#62]
There are 2 deprecated packages present in this project
```js
 WARN  deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```

https://github.com/vite-pwa/sveltekit/blob/2286b7a1fe4f1f9f23752df31a60fdc61024e7be/pnpm-lock.yaml#L4824
https://github.com/vite-pwa/sveltekit/blob/2286b7a1fe4f1f9f23752df31a60fdc61024e7be/pnpm-lock.yaml#L5014

**Comment by userquin** [comment]
we don't have those packages installed: https://github.com/vite-pwa/sveltekit/blob/main/package.json#L52-L71

**Comment by Naviamold1** [comment]
> we don't have those packages installed: https://github.com/vite-pwa/sveltekit/blob/main/package.json#L52-L71

They are in the [pnpm-lock.json](https://github.com/vite-pwa/sveltekit/blob/main/pnpm-lock.yaml) file.

https://github.com/vite-pwa/sveltekit/blob/2286b7a1fe4f1f9f23752df31a60fdc61024e7be/pnpm-lock.yaml#L4824

https://github.com/vite-pwa/sveltekit/blob/2286b7a1fe4f1f9f23752df31a60fdc61024e7be/pnpm-lock.yaml#L5014

**Comment by wolfsgrove** [comment]
It's a `workbox-build` dependency issue in `vite-plugin-pwa`: https://github.com/GoogleChrome/workbox/issues/3228#issue-1776864745
