### ISSUE TITLE
Need Additional Dependency Installation?

### ISSUE THREAD

**Issue by XIYO** [vite-pwa/sveltekit#88]
Hello,

I am a beginner developer who is not very familiar with Node and Vite.

When I installed `@vite-pwa/sveltekit` in my Svelte project (which is in a completely fresh state) and ran `vite dev`, I encountered a `Cannot find package 'fast-glob'` error. 

I’m wondering if I should look into the "externals" field in the `/build.config.ts` file and manually install those dependencies? Since no specific versions are mentioned, should I just install the latest versions?

If so, why isn’t this step included in the "README.md"? 

I have two guesses:
- It might be an oversight in the documentation.
- Or maybe there’s something wrong with my project setup.

P.S. I resolved the issue by running `pnpm add fast-glob vite vite-plugin-pwa workbox-build`.

Thank you for your assistance!

**Comment by userquin** [comment]
@XIYO should be fixed in v0.6.6
